### ISSUE TITLE
PyPI Source Distribution Missing Templates / CSS

### ISSUE THREAD

**Issue by jvantuyl** [seomoz/shovel#12]
The source dist on PyPI is missing the templates.  Not sure why.  Possibly due to older versions of distutils not including package data without a MANIFEST.in.  Highly depends on versions of stuff used when you build the sdist.

When I build the sdist myself it works, so I don't have much of an explanation.

**Comment by b4hand** [comment]
I believe this is related to shovel-server which is no longer packaged as part of shovel.
