### ISSUE TITLE
Directory-resident tasks and global context?

### ISSUE THREAD

**Issue by jonathaneunice** [seomoz/shovel#18]
I see how `shovel` works to execute tasks in the local directory. The handling of task definitions within a `shovel` directory is a bit more confusing, though. If I have a file `shovel/one.py` then I must invoke tasks as `shovel one.taskname`. Neither dropping the tasks into `shovel/shovel.py` nor into `shovel/__init__.py` allows me to do the simpler, unqualified `shovel taskname` style invocation. The ability to modularize / categorize functions seems great--but less so if it simultaneously evaporates the ability to do quick, unqualified access to the highest-level, most-used tasks.

Also, it seems that this might be very helpful as a front-end for various utility functions I need to run, but that would require a "global home base" like a `~/.shovel` directory, and a means of running "top level" tasks without qualified names (as described above). Otherwise, I would constantly have to do some sort of `cd ~/shovel` before executing a shovel command, losing the current working directory (typical context in which tasks should be run), and re-complexifying task invocation.

**Comment by b4hand** [comment]
Looks like this was resolved by #19.
