### ISSUE TITLE
pip install shovel does not work

### ISSUE THREAD

**Issue by mckoss** [seomoz/shovel#4]
```
$ pip install bottle
$ pip install shovel
$ shovel-server
```
- Try to open localhost:3000/help

Result: Can't find help.tpl.

When installing using pip, it looks like the templates subdirectory is not copied into site-packages.

Note that using easy_install seems to work fine.

```
$ easy_install shovel
```

**Comment by b4hand** [comment]
I'm going to close this out since shovel-server is no longer packaged in shovel at all.
